name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-report:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          cd ./reports
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/dist
          publish_branch: gh-pages
